{
  parserClass="com.github.mtwango.intellijscpplugin.language.parser.SphereScriptParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="SphereScript"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.mtwango.intellijscpplugin.language.psi"
  psiImplPackage="com.github.mtwango.intellijscpplugin.language.psi.impl"

  elementTypeHolderClass="com.github.mtwango.intellijscpplugin.language.psi.SphereScriptTypes"
  elementTypeClass="com.github.mtwango.intellijscpplugin.language.psi.SphereScriptElementType"
  tokenTypeClass="com.github.mtwango.intellijscpplugin.language.psi.SphereScriptTokenType"

  psiImplUtilClass="com.github.mtwango.intellijscpplugin.language.psi.impl.SphereScriptPsiImplUtil"
}

spherescriptFile ::= item_*

private item_ ::= (property|TRIGGER|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  mixin="com.github.mtwango.intellijscpplugin.language.psi.impl.SphereScriptNamedElementImpl"
  implements="com.github.mtwango.intellijscpplugin.language.psi.SphereScriptNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier]
}
